Multifits merge to release-0.2.0 after taking care of precommit changes
GreenBankObservatory/dysh pull request #111
Opened 2023-11-16 19:35 UTC by mpound

2023-11-16 19:36 UTC, mpound commented
There are still some files that are conflicted but far fewer than before.

2023-11-16 20:16 UTC, tchamberlin requested changes
Bailing out of this review; we need to sort out the black formatting issues

2023-11-16 20:16 UTC, tchamberlin commented on .github/workflows/pre-commit.yml
> +        python-version: '3.9'
Doesn't match the version in `.pre-commit.config.yaml` (3.10)

2023-11-16 20:16 UTC, tchamberlin commented on .github/workflows/hatch-and-pytest.yml
> +    branches: [ "main", "release-0.1.0", "cat-devel", "mwp-devel", "pedro-devel", "evan-devel" ]
Prefer wildcards here, e.g. `"main*"` and `"release-*"`; would also resolve the conflict

2023-11-16 20:16 UTC, tchamberlin commented on gui/app.py
Lots of changes here I'm not really in a position to analyze. Do we need to resolve conflicts or can we just keep the version in `multifits`?

2023-11-16 20:16 UTC, tchamberlin commented on attic/sdfitsload.py
Lots of changes here I'm not really in a position to analyze. Do we need to resolve conflicts or can we just keep the version in `multifits`?

2023-11-16 20:16 UTC, tchamberlin commented on benchmark/makeplots.py
I'm not really sure what to do here. Black clearly has not been run on the files in whatever version of `release-0.2.0` this is referencing. But I can see that the current `release-0.2.0` is formatted as expected

2023-11-16 20:33 UTC, mpound commented
ok let me work on this some more. 
@vcatlett you should address Thomas's question about gui/app.py

2023-11-17 18:28 UTC, tchamberlin commented on .pre-commit-config.yaml
> +        exclude: ^notebooks/
Sorry, this is confusing -- as per email, this is referencing only line 27; 28 is fine

2023-11-17 19:04 UTC, closed without merging