Fix invalid escape sequences in docstrings
GreenBankObservatory/dysh pull request #119
Opened 2023-11-20 20:47 UTC by tchamberlin

These were resulting in SyntaxWarning in Python 3.12:

```plain
dysh/src/dysh/plot/specplot.py:10: SyntaxWarning: invalid escape sequence '\*'
  """
dysh/src/dysh/plot/specplot.py:91: SyntaxWarning: invalid escape sequence '\*'
  """
dysh/src/dysh/plot/specplot.py:167: SyntaxWarning: invalid escape sequence '\*'
  """Set x and y labels according to spectral units
dysh/src/dysh/spectra/scan.py:155: SyntaxWarning: invalid escape sequence '\d'
  """Average all polarizations in all scans in this ScanBlock
dysh/src/dysh/spectra/scan.py:175: SyntaxWarning: invalid escape sequence '\d'
  """Average all times and polarizations in all scans this ScanBlock
dysh/src/dysh/spectra/scan.py:697: SyntaxWarning: invalid escape sequence '\d'
  """
```

2023-11-20 21:21 UTC, mpound commented
Yeah, these were to have proper **kwargs shown in documentation.  I'll accept this change and we can see what it does to docs.

2023-11-20 21:23 UTC, mpound requested changes
The double \ in the :math: lines is incorrect. These are latex symbols with a single \

2023-11-20 22:35 UTC, tchamberlin commented
Ah okay! I've reverted all of this and changed to raw-string-literal docstrings. These are already being used elsewhere, and the numpy examples use it as well: https://github.com/numpy/numpydoc/blob/main/doc/example.py

2023-11-21 01:01 UTC, mpound approved these changes
Also, FYI the r at the beginning of some docstrings allows one to use latex math markup in the documentation itself.

2023-11-21 01:01 UTC, merged