Issue 256
GreenBankObservatory/dysh pull request #264
Opened 2024-05-30 00:03 UTC by astrofle

fix: add support for AzEl observations

Adds check for empty `RADESYS` column and functionality to handle AltAz (AzEl) coordinate frame

Still needs tests, but it can handle Issue #256.

2024-05-30 18:21 UTC, etsmit requested changes
Two things:
1. Add more to the warning (either at the GBTFITSLoad step or when changing velocity frames) that the Az/El values are invalid and will result in an incorrect frequency shift. This could be detected as a separate case from drift scans by detecting when e.g. elevation <4.9. (Or when az/el values are unchanging?)
2. Possibly add the scan numbers corresponding to the blank radesys rows to the warning message, since the antenna manager can be taken in/out over the course of a session. For example, "No RADESYS specified for scans X,Y,Z; assuming AltAz"

2024-06-06 12:46 UTC, astrofle commented
The last update also adds support for HaDEC observations.

2024-06-06 13:03 UTC, etsmit commented on src/dysh/fits/gbtfitsload.py
> +            lambda scans, a, coord, limit: f"""Scan(s) {scans} have {a} {coord} below {limit}. The GBT does not go that low. Any operations that rely on the sky coordinates are likely to be innacurat
"inaccurate"

2024-06-06 13:51 UTC, etsmit approved these changes

2024-06-07 19:25 UTC, astrofle commented
@mpound is this fix acceptable?

2024-06-07 20:22 UTC, mpound approved these changes
Looks good to me.

2024-06-07 20:34 UTC, merged